### ISSUE TITLE
Sample

### ISSUE THREAD

**Issue by kooyaniks** [anthonygacis/psgc-js#18]
Hi Sir do you have a sample page for this? The demo uploaded is in GIF file. TIA

**Comment by anthonygacis** [comment]
oh I will create one.

**Comment by kooyaniks** [comment]
Thank you Sir! Will wait for this as I'm creating a simple CRUD web based app that will save and update the saved data (eg. PSGC).

**Comment by anthonygacis** [comment]
Hi @kooyaniks, sorry for the late update. kinda busy
if you are still interested in the docs here's the link https://psgc-js.vercel.app/
It is still in beta.

Thanks,
